import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
//import Home from './components/Home.jsx'
// import Vegetables from './components/Vegetables.jsx'
// import Billing from './components/Billing.jsx'
// import UserHeader from './components/UserHeader.jsx'
// import Admin from './components/Admin.jsx'
// import Dropdown from './components/Dropdown.jsx'
// import Fruits from './components/Fruits.jsx'
//  import Grocery from './components/Grocery.jsx'
 //import Tomato from './components/Tomato.jsx'
// import Kitchen from './components/Kitchen.jsx'
// import Dryfruits from './components/Dryfruits.jsx'
// import Dairy from './components/Dairy.jsx'
// import Snacks from './components/Snacks.jsx'
// import Login from './components/Login.jsx'
// import Signup from './components/Signup.jsx'
// import Categories from './components/Categories.jsx'
// import AdminHeader from './components/AdminHeader.jsx'
// import Skinitems from './components/Skinitems.jsx'
import Fr_App from './components/Master.jsx'
ReactDOM.createRoot(document.getElementById('root')).render(
  <Fr_App></Fr_App>
)
